import {
  FILTER_NAMES,
  ENTITY_TYPES,
  SORTING_DIRECTION,
  TABLE_ORDER_COLUMNS_SORTED,
  TABLE_DISPUTE_COLUMNS_SORTED,
} from '@/constants';

const filters = {
  [ENTITY_TYPES.ORDERS]: {
    [FILTER_NAMES.SEARCH_ORDERS]: '',
    [FILTER_NAMES.SORT]: TABLE_ORDER_COLUMNS_SORTED.ORDER_NUMBER,
    [FILTER_NAMES.ORDER]: SORTING_DIRECTION.ASC,
    [FILTER_NAMES.ORDER_STATUS]: null,
  },
  [ENTITY_TYPES.DISPUTES]: {
    [FILTER_NAMES.SEARCH_DISPUTES]: '',
    [FILTER_NAMES.SORT]: TABLE_DISPUTE_COLUMNS_SORTED.ID,
    [FILTER_NAMES.ORDER]: SORTING_DIRECTION.ASC,
    [FILTER_NAMES.DISPUTE_TYPE_IDS]: null,
    [FILTER_NAMES.FISCAL_PERIOD_ID]: null,
    [FILTER_NAMES.CREATED_FROM]: '',
    [FILTER_NAMES.CREATED_TO]: '',
  },
  [ENTITY_TYPES.RESUBMISSION]: {
    [FILTER_NAMES.SEARCH_DISPUTES]: '',
    [FILTER_NAMES.SORT]: TABLE_DISPUTE_COLUMNS_SORTED.ID,
    [FILTER_NAMES.ORDER]: SORTING_DIRECTION.ASC,
    [FILTER_NAMES.DISPUTE_TYPE_IDS]: null,
    [FILTER_NAMES.FISCAL_PERIOD_ID]: null,
    [FILTER_NAMES.CREATED_FROM]: '',
    [FILTER_NAMES.CREATED_TO]: '',
  },
};

export default itemType => ({ ...filters[itemType] } || {});
