apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-reconcil-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-reconcil-static
  template:
    metadata:
      labels:
        app: dev-reconcil-static
    spec:
#      nodeSelector:
#        env: applications
      containers:
      - name: dev-reconcil-static
        image: xyziesdevregistry.azurecr.io/xyz-fe-reconciliation-dev:0.0.0.0
        resources:
          requests:
            cpu: 150m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1024Mi
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: dev-reconcil-static
spec:
  ports:
  - protocol: "TCP"
    port: 8070
    targetPort: 8070
    name: "http"
  selector:
    app: dev-reconcil-static
  clusterIP: 172.20.0.70
