import i18n from '@/i18n';

/* eslint-disable-next-line import/prefer-default-export */
export const getOrdersTableColumns = () => [
  {
    name: 'ordersNumber',
    field: 'orderNumber',
    class: 'text',
    title: i18n.t('orders.number'),
    width: '4',
    minWidth: '120px',
  },
  {
    name: 'accountNumber',
    field: 'accountNumber',
    class: 'text',
    title: i18n.t('orders.account.number'),
    width: '4',
    minWidth: '120px',
  },
  {
    name: 'serviceName',
    field: 'sevice.name',
    class: 'text',
    title: i18n.t('orders.service.name'),
    width: '17',
    minWidth: '90px',
  },
  {
    name: 'orderedUnits',
    field: 'orderedUnits',
    class: 'text',
    title: i18n.t('orders.ordered.units'),
    width: '4',
    minWidth: '110px',
  },
  {
    name: 'installedUnits',
    field: 'installedUnits',
    class: 'text',
    title: i18n.t('orders.installed.units'),
    width: '4',
    minWidth: '110px',
  },
  {
    name: 'orderStatus',
    field: 'orderStatus',
    class: 'text',
    title: i18n.t('orders.order.status'),
    width: '4',
    minWidth: '110px',
  },
  {
    name: 'creationAge',
    field: 'creationAge',
    class: 'text',
    title: i18n.t('orders.age.after.order'),
    width: '4',
    minWidth: '110px',
  },
  {
    name: 'installationAge',
    field: 'installationAge',
    class: 'text',
    title: i18n.t('orders.age.after.installation'),
    width: '5',
    minWidth: '130px',
  },
  {
    name: 'expectedComission',
    field: 'expectedComission',
    class: 'text',
    title: i18n.t('orders.expected.comission'),
    width: '5',
    minWidth: '120px',
  },
  {
    name: 'recevedComission',
    field: 'recevedComission',
    class: 'text',
    title: i18n.t('orders.recieved.comisson'),
    width: '5',
    minWidth: '120px',
  },
  {
    name: 'orderDifference',
    fieldType: 'orderDifference',
    class: 'text',
    title: i18n.t('orders.difference'),
    width: '4',
    minWidth: '120px',
  },
];
