import i18n from '@/i18n';
import { TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED } from '@/constants';

export default () => [
  {
    name: 'creatorName',
    field: 'creatorName',
    class: 'text',
    title: i18n.t('dispute.creator.name'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.CREATOR,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'entered',
    field: 'entered',
    class: 'text',
    title: i18n.t('opened.disputes'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.ENTERED,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'units',
    field: 'units',
    class: 'text',
    title: i18n.t('number.of.units'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.UNITS,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'closed',
    field: 'closed',
    class: 'text',
    title: i18n.t('closed.disputes'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.CLOSED,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'closedPercent',
    field: 'closedPercent',
    fieldType: 'percent',
    class: 'text',
    title: i18n.t('closed.disputes.in'),
    width: '3',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.CLOSED_PERCENT,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'approved',
    field: 'approved',
    class: 'text',
    title: i18n.t('approved.by.xyz'),
    width: '3',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.APPROVED,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'approvedPercent',
    field: 'approvedPercent',
    fieldType: 'percent',
    class: 'text',
    title: i18n.t('approved.by.xyz.in'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.APPROVED_PERCENT,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'rejected',
    field: 'rejected',
    class: 'text',
    title: i18n.t('rejected.by.xyz'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.REJECTED,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'rejectedPercent',
    field: 'rejectedPercent',
    fieldType: 'percent',
    options: {
      withIndicator: true,
      bad: 35,
      average: 70,
    },
    class: 'text',
    title: i18n.t('rejected.by.xyz.in'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.REJECTED_PERCENT,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'approvedComission',
    field: 'approvedComission',
    class: 'text',
    title: i18n.t('approved.commission'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.APPROVED_COMMISSION,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'resubmited',
    field: 'resubmited',
    class: 'text',
    title: i18n.t('number.of.resubmitted'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.RESUBMITTED,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'resubmitedPercent',
    field: 'resubmitedPercent',
    fieldType: 'percent',
    class: 'text',
    title: i18n.t('number.of.resubmitted.in'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.RESUBMITTED_PERCENT,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'pending',
    field: 'pending',
    class: 'text',
    title: i18n.t('waiting.for.spectrum.answer'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.PENDING,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'pendingPercent',
    field: 'pendingPercent',
    fieldType: 'percent',
    class: 'text',
    title: i18n.t('waiting.for.spectrum.answer.in'),
    width: '4',
    minWidth: '16px',
    sortingFieldName: TABLE_DISPUTES_BY_SUBMITTERS_COLUMNS_SORTED.PENDING_PERCENT,
    fieldHeaderType: 'sortingHeader',
  },
];
