export default () => [
  {
    name: 'carierOrderNumber',
    field: 'carierOrderNumber',
    fieldType: 'default',
    class: 'text',
    title: 'carrier.order.number',
    width: '4',
    minWidth: '16px',
  },
  {
    name: 'service',
    field: 'service',
    class: 'text',
    title: 'disputes.service.name',
    width: '4',
    minWidth: '16px',
  },
  {
    name: 'installedUnits',
    field: 'installedUnits',
    class: 'text',
    title: 'orders.installed.units',
    width: '4',
    minWidth: '70px',
  },
  {
    name: 'installationDate',
    field: 'installationDate',
    fieldType: 'dateYearMonthDay',
    class: 'text',
    title: 'dispute.installation.date',
    width: '5',
    minWidth: '60px',
  },
  {
    name: 'ageAfterInstallation',
    field: 'ageAfterInstallation',
    fieldType: 'installationAgeCell',
    class: 'text',
    title: 'orders.age.after.installation',
    width: '4',
    minWidth: '90px',
  },
  {
    name: 'reseivedCommission',
    field: 'reseivedCommission',
    fieldType: 'price',
    class: 'text',
    title: 'disputes.recieved.comisson',
    width: '5',
    minWidth: '85px',
  },
];
